--------------------------------------------------------
--  파일이 생성됨 - 금요일-4월-19-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CS_QNABOARD_IMG
--------------------------------------------------------

  CREATE TABLE "IBARA"."CS_QNABOARD_IMG" 
   (	"QBNO" NUMBER, 
	"QBFILECODE" VARCHAR2(50 BYTE), 
	"FILESRC" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into IBARA.CS_QNABOARD_IMG
SET DEFINE OFF;
Insert into IBARA.CS_QNABOARD_IMG (QBNO,QBFILECODE,FILESRC) values (37,'2','1713098283199_퀵견적 관련 사진1.png');
Insert into IBARA.CS_QNABOARD_IMG (QBNO,QBFILECODE,FILESRC) values (38,'3','1713100146078_퀵견적 관련 사진1.png');
Insert into IBARA.CS_QNABOARD_IMG (QBNO,QBFILECODE,FILESRC) values (39,'4','1713100632845_로그인 관련 1.png');
Insert into IBARA.CS_QNABOARD_IMG (QBNO,QBFILECODE,FILESRC) values (40,'5','1713100928715_업체 관련 1.png');
Insert into IBARA.CS_QNABOARD_IMG (QBNO,QBFILECODE,FILESRC) values (41,'6','1713103080251_소품샵 관련1.png');
--------------------------------------------------------
--  DDL for Index SYS_C007235
--------------------------------------------------------

  CREATE UNIQUE INDEX "IBARA"."SYS_C007235" ON "IBARA"."CS_QNABOARD_IMG" ("QBNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CS_QNABOARD_IMG
--------------------------------------------------------

  ALTER TABLE "IBARA"."CS_QNABOARD_IMG" ADD PRIMARY KEY ("QBNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
